
source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
inhibit_all_warnings!

plugin 'cocoapods-user-defined-build-types', {
  verbose: true
}
enable_user_defined_build_types!

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :generate_multiple_pod_projects => true

target 'Lnssh' do
  inherit! :search_paths
  config = use_native_modules!
  
  use_react_native!(:path => config["reactNativePath"])
  pod 'PromiseKit', :build_type => :dynamic_framework
  pod 'Starscream', :build_type => :dynamic_framework,git: 'https://github.com/daltoniam/Starscream' , tag: '3.1.1'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'WHToast','~>0.1.0'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    flipper_post_install(installer)
  end
end